classdef tlmstudioChat < matlab.unittest.TestCase
% Tests for openAIChat with LM Studio server

%   Copyright 2023-2025 The MathWorks, Inc.

    properties(TestParameter)
        StringInputs = struct('string',{"hi"},'char',{'hi'},'cellstr',{{'hi'}});
    end

    properties
        lmstudioEndpoint = "http://localhost:1134/v1/chat/completions";
        lmstudioAPIKey = "lm-studio";
        lmstudioModel = "local-model";
    end
    
    methods(Test)
        % Basic constructor tests
        function constructChatWithLMStudioEndpoint(testCase)
            chat = openAIChat("Test system prompt", ...
                ModelName=testCase.lmstudioModel, ...
                EndPoint=testCase.lmstudioEndpoint, ...
                APIKey=testCase.lmstudioAPIKey);
            
            testCase.verifyEqual(chat.ModelName, testCase.lmstudioModel);
            testCase.verifyEqual(chat.EndPoint, testCase.lmstudioEndpoint);
            % Note: APIKey is private, so we can't verify it directly
        end

        function constructChatWithAllNVPForLMStudio(testCase)
            functions = openAIFunction("testFunction", "A test function");
            functions = addParameter(functions, "param1", type="string", description="Test parameter");
            
            temperature = 0.7;
            topP = 0.9;
            stop = ["[END]", "."];
            presenceP = 0.1;
            frequenceP = 0.1;
            systemPrompt = "This is a system prompt for LM Studio";
            timeout = 30;
            
            chat = openAIChat(systemPrompt, ...
                Tools=functions, ...
                ModelName=testCase.lmstudioModel, ...
                Temperature=temperature, ...
                TopP=topP, ...
                StopSequences=stop, ...
                APIKey=testCase.lmstudioAPIKey, ...
                FrequencyPenalty=frequenceP, ...
                PresencePenalty=presenceP, ...
                TimeOut=timeout, ...
                EndPoint=testCase.lmstudioEndpoint);

            testCase.verifyEqual(chat.ModelName, testCase.lmstudioModel);
            testCase.verifyEqual(chat.Temperature, temperature);
            testCase.verifyEqual(chat.TopP, topP);
            testCase.verifyEqual(chat.StopSequences, stop);
            testCase.verifyEqual(chat.FrequencyPenalty, frequenceP);
            testCase.verifyEqual(chat.PresencePenalty, presenceP);
            testCase.verifyEqual(chat.EndPoint, testCase.lmstudioEndpoint);
        end

        function generateAcceptsSingleStringAsInput(testCase, StringInputs)
            chat = openAIChat("You are a helpful assistant", ...
                ModelName=testCase.lmstudioModel, ...
                EndPoint=testCase.lmstudioEndpoint, ...
                APIKey=testCase.lmstudioAPIKey);
            
            response = testCase.verifyWarningFree(...
                @()generate(chat, StringInputs));
            testCase.verifyClass(response, 'string');
            testCase.verifyGreaterThan(strlength(response), 0);
        end

        function generateAcceptsMessagesAsInput(testCase)
            chat = openAIChat("You are a helpful assistant", ...
                ModelName=testCase.lmstudioModel, ...
                EndPoint=testCase.lmstudioEndpoint, ...
                APIKey=testCase.lmstudioAPIKey);
            
            messages = messageHistory;
            messages = addUserMessage(messages, "Hello, how are you?");

            response = testCase.verifyWarningFree(...
                @()generate(chat, messages));
            testCase.verifyClass(response, 'string');
            testCase.verifyGreaterThan(strlength(response), 0);
        end

        function generateWithCustomParameters(testCase)
            chat = openAIChat("You are a helpful assistant", ...
                ModelName=testCase.lmstudioModel, ...
                EndPoint=testCase.lmstudioEndpoint, ...
                APIKey=testCase.lmstudioAPIKey);
            
            response = testCase.verifyWarningFree(...
                @()generate(chat, "Say 'test'", ...
                    Temperature=0.1, ...
                    MaxNumTokens=50));
            testCase.verifyClass(response, 'string');
            testCase.verifyGreaterThan(strlength(response), 0);
        end

        function testFunctionCalling(testCase)
            % Create a simple function
            func = openAIFunction("get_weather", "Get current weather for a location");
            func = addParameter(func, "location", type="string", description="The city and state/country");
            
            chat = openAIChat("You are a helpful assistant that can check weather.", ...
                ModelName=testCase.lmstudioModel, ...
                EndPoint=testCase.lmstudioEndpoint, ...
                APIKey=testCase.lmstudioAPIKey, ...
                Tools=func);
            
            [response, message] = testCase.verifyWarningFree(...
                @()generate(chat, "What's the weather like in New York?"));
            
            % Check if function was called (response might be empty for function calls)
            if isfield(message, 'tool_calls') && ~isempty(message.tool_calls)
                testCase.verifyEqual(string(message.tool_calls(1).function.name), "get_weather");
                testCase.verifyTrue(contains(message.tool_calls(1).function.arguments, "New York"));
            else
                % If no function call, just verify we got a response
                testCase.verifyClass(response, 'string');
            end
        end

        function testModelValidationSkippedForLMStudio(testCase)
            % Test that custom model names work with LM Studio endpoint
            customModelName = "custom-local-model-123";
            
            % This should not throw an error even though the model is not in OpenAI's list
            chat = testCase.verifyWarningFree(...
                @()openAIChat("Test prompt", ...
                    ModelName=customModelName, ...
                    EndPoint=testCase.lmstudioEndpoint, ...
                    APIKey=testCase.lmstudioAPIKey));
            
            testCase.verifyEqual(chat.ModelName, customModelName);
        end

        function testResponseFormatText(testCase)
            chat = openAIChat("You are a helpful assistant", ...
                ModelName=testCase.lmstudioModel, ...
                EndPoint=testCase.lmstudioEndpoint, ...
                APIKey=testCase.lmstudioAPIKey, ...
                ResponseFormat="text");
            
            response = testCase.verifyWarningFree(...
                @()generate(chat, "Hello"));
            testCase.verifyClass(response, 'string');
        end

        function testInvalidTemperature(testCase)
            % Test invalid temperature values
            testCase.verifyError(...
                @() openAIChat("Test prompt", ...
                    Temperature=-1, ...
                    EndPoint=testCase.lmstudioEndpoint, ...
                    APIKey=testCase.lmstudioAPIKey, ...
                    ModelName=testCase.lmstudioModel), ...
                "MATLAB:expectedNonnegative");
        end

        function testInvalidTopP(testCase)
            % Test invalid TopP values
            testCase.verifyError(...
                @() openAIChat("Test prompt", ...
                    TopP=2, ...
                    EndPoint=testCase.lmstudioEndpoint, ...
                    APIKey=testCase.lmstudioAPIKey, ...
                    ModelName=testCase.lmstudioModel), ...
                "MATLAB:notLessEqual");
        end
    end
end